import type { Palette, PixelMap } from "../svg.ts";

export const ART_PAL: Palette = {
  K: "#14142B",
  W: "#FFFFFF",
  T: "#3FE0C5",
  t: "#1C9E8C",
  Y: "#D7FFF6",
  N: "#262A57",
  n: "#3E4590",
  m: "#161834",
  C: "#5CF2D2",
  S: "#FFE27A",
  O: "#FFB43F",
  M: "#F6F1CF",
  o: "#D3CC9A",
  E: "#3BA55C",
  e: "#74D98F",
  d: "#25774A",
  U: "#8A5530",
  u: "#5E3A20",
  R: "#E5484D",
  r: "#A83036",
  D: "#8B8FA8",
  G: "#FFC83D",
  g: "#C98A1A",
  Q: "#EFE9D8",
  q: "#BDB49A",
  B: "#5462E8",
  b: "#3A45B5",
  w: "#A9DDFF",
  v: "#6FA8D6",
};

/** 4 frames (10×9) لدوران الجوهرة */
export const GEM: readonly PixelMap[] = [
  [
    "...KKKK...",
    "..KYYTTK..",
    ".KYYTTTtK.",
    "KYTTTTTttK",
    "KTTTTTTttK",
    ".KTTTTttK.",
    "..KTTttK..",
    "...KTtK...",
    "....KK....",
  ],
  [
    "....KK....",
    "...KYTK...",
    "..KYYTtK..",
    "..KYTTtK..",
    "..KTTTtK..",
    "..KTTttK..",
    "...KTtK...",
    "...KTtK...",
    "....KK....",
  ],
  [
    "....KK....",
    "...KTtK...",
    "...KTtK...",
    "...KTtK...",
    "...KTtK...",
    "...KTtK...",
    "...KTtK...",
    "...KTtK...",
    "....KK....",
  ],
  [
    "....KK....",
    "...KTYK...",
    "..KtTYYK..",
    "..KtTTYK..",
    "..KtTTTK..",
    "..KttTTK..",
    "...KtTK...",
    "...KtTK...",
    "....KK....",
  ],
];

/** ⚠️ ترتيب المفاتيح = ترتيب الناتج. لازم يضل: block, sun, moon, tree, mailbox, flag, academy, office, diploma */
export const ART = {
  block: [
    "KKKKKKKKKKKKKKKK",
    "KnnnnnnnnnnnnnmK",
    "KnNNNNNNNNNNNNmK",
    "KnNnNNNNNNNNnNmK",
    "KnNNNNNNNNNNNNmK",
    "KnNNCNNNCNCNNNmK",
    "KnNCNNNNCNNCNNmK",
    "KnCNNNNCNNNNCNmK",
    "KnNCNNCNNNNCNNmK",
    "KnNNCNCNNNCNNNmK",
    "KnNNNNNNNNNNNNmK",
    "KnNNNNNNNNNNNNmK",
    "KnNnNNNNNNNNnNmK",
    "KnNNNNNNNNNNNNmK",
    "KmmmmmmmmmmmmmmK",
    "KKKKKKKKKKKKKKKK",
  ],
  sun: [
    ".......OO.......",
    ".......OO.......",
    "..O..........O..",
    "...O.OOSSOO.O...",
    "....OSSSSSSO....",
    "...OSWWSSSSSO...",
    "...OSWSSSSSSO...",
    "OO.SSSSSSSSSS.OO",
    "OO.SSSSSSSSSS.OO",
    "...OSSSSSSSSO...",
    "...OSSSSSSSSO...",
    "....OSSSSSSO....",
    "...O.OOSSOO.O...",
    "..O..........O..",
    ".......OO.......",
    ".......OO.......",
  ],
  moon: [
    "................",
    "................",
    ".....oo.........",
    "...ooM..........",
    "...oMM..........",
    "..oMMM..........",
    "..oMMM..........",
    "..oMMM..........",
    "..oMMMM.........",
    "..oMoMMM........",
    "..oMMMMMM.......",
    "...oMMMoMMMMM...",
    "...ooMoMMMMMM...",
    ".....ooooMM.....",
    "................",
    "................",
  ],
  tree: [
    ".....KKKKKK.....",
    "...KKeeeEEEKK...",
    "..KeeeeEEEEEEK..",
    ".KeeeEEEEEEEEEK.",
    ".KeeEEEEEEEEEdK.",
    "KeeEEEEEEEEEEEdK",
    "KeEEEEEEEEEEEddK",
    "KEEEEEEEEEEEEddK",
    "KEEEEEEEEEEEdddK",
    ".KEEEEEEEEEEddK.",
    ".KdEEEEEEEEdddK.",
    "..KddEEEEdddKK..",
    "...KKddddddKK...",
    ".....KKUuKK.....",
    "......KUuK......",
    "......KUuK......",
    "......KUuK......",
    "......KUuK......",
    ".....KUUuuK.....",
    "................",
  ],
  mailbox: [
    "..........KK.",
    "..........KGK",
    "..KKKKKKK.KGK",
    ".KRRRRRRRKKKK",
    "KRRRRRRRRRrK.",
    "KRWWWWWWWRrK.",
    "KRRRRRRRRRrK.",
    "KRRRRRRRRRrK.",
    "KrrrrrrrrrrK.",
    ".KKKKKKKKKK..",
    ".....KUuK....",
    ".....KUuK....",
    ".....KUuK....",
    ".....KUuK....",
    ".....KUuK....",
    "....KUUuuK...",
  ],
  flag: [
    "KK..........",
    "KDKKKKKK....",
    "KDKGGGGGKK..",
    "KDKGGGGGGGK.",
    "KDKGGGGggK..",
    "KDKGGgggK...",
    "KDKKKKKK....",
    "KDK.........",
    "KDK.........",
    "KDK.........",
    "KDK.........",
    "KDK.........",
    "KDK.........",
    "KDK.........",
    "KKKK........",
  ],
  academy: [
    "........KK........",
    "......KKBBKK......",
    "....KKBBBBBBKK....",
    "..KKBBBBBBBBBbKK..",
    "KKbbbbbbbbbbbbbbKK",
    "KQQQQQQQQQQQQQQQqK",
    "KKKKKKKKKKKKKKKKKK",
    ".KQKKQKKQKKQKKQK..",
    ".KQqKQqKQqKQqKQqK.",
    ".KQqKQqKQqKQqKQqK.",
    ".KQqKQqKQqKQqKQqK.",
    ".KQqKQqKQqKQqKQqK.",
    "KKKKKKKKKKKKKKKKKK",
    "KQQQQQQQQQQQQQQQqK",
    "KqqqqqqqqqqqqqqqqK",
    "KKKKKKKKKKKKKKKKKK",
  ],
  office: [
    "....KKKKKK....",
    "....KDDDDK....",
    "..KKKKKKKKKK..",
    "..KwvKwvKwvK..",
    "..KDDDDDDDDK..",
    "..KwvKwvKwvK..",
    "..KDDDDDDDDK..",
    "..KwvKwvKwvK..",
    "..KDDDDDDDDK..",
    "..KwvKwvKwvK..",
    "..KDDDDDDDDK..",
    "..KwvKwvKwvK..",
    "..KDDDDDDDDK..",
    "..KDDKKKKDDK..",
    "..KDDKwvKDDK..",
    "KKKKKKKKKKKKKK",
  ],
  diploma: [
    "KKKKKKKKKKKKKK",
    "KQQQQQQQQQQQqK",
    "KQKKKKKKKQQQqK",
    "KQQQQQQQQQQQqK",
    "KQKKKKKKQQQQqK",
    "KQQQQQQQQRRRqK",
    "KQKKKKQQRGGGRK",
    "KqqqqqqqRGGGRK",
    "KKKKKKKKKRRRKK",
    ".........RKRK.",
    ".........K.K..",
  ],
} as const satisfies Record<string, PixelMap>;

export type ArtName = keyof typeof ART;
