import type { Palette, PixelMap } from "../svg.ts";

/** ألوان الأرض والـ scenery المولّد (غيوم، تلال، جبال، skyline، نجوم) */
export const SCENE_PAL: Palette = {
  w: "#FFFFFF",
  c: "#D2EAFB",
  H: "#4FAE69",
  h: "#86D88F",
  d: "#3D9059",
  A: "#8DB4E2",
  a: "#7298C8",
  n: "#F2F8FF",
  N: "#CFE0F2",
  Q: "#7387C8",
  q: "#5B6EAF",
  y: "#FFE9A8",
  z: "#A9B9E6",
  W: "#FFFFFF",
  Y: "#FFE9A8",
  l: "#8CE070",
  G: "#58C44B",
  g: "#3A9A3A",
  D: "#B0622F",
  x: "#8A4A22",
  o: "#D08A4E",
  X: "#6A3518",
};

export const GROUND: PixelMap = [
  "llllllllllllllll",
  "lGGlGGGlGGGlGGGl",
  "GGGGGGGGGGGGGGGG",
  "GGgGGGGGgGGGGgGG",
  "gggGgGGgggGgGggg",
  "XgXggXgXXgXggXgX",
  "DXDXDDXDDXDXDDXD",
  "DDDDDDDDDDDDDDDD",
  "DDoDDDDDDxDDDDDD",
  "DDDDDDDDDDDDDoDD",
  "DDDDxDDDDDDDDDDD",
  "DoDDDDDDDDoDDDxD",
  "DDDDDDDxDDDDDDDD",
  "DDDDDDDDDDDDDDDD",
  "DxDDDoDDDDDxDDDD",
  "DDDDDDDDDDDDDDDD",
];

export const DIRT: PixelMap = [
  "DDDDDDDDDDDDDDDD",
  "DDoDDDDDDxDDDDDD",
  "DDDDDDDDDDDDDoDD",
  "DDDDxDDDDDDDDDDD",
  "DoDDDDDDDDoDDDxD",
  "DDDDDDDxDDDDDDDD",
  "DDDDDDDDDDDDDDDD",
  "DxDDDoDDDDDxDDDD",
  "DDDDDDDDDDDDDDDD",
  "DDDDDDDDDoDDDDDD",
  "DDDxDDDDDDDDDxDD",
  "DDDDDDoDDDDDDDDD",
  "DoDDDDDDDDDxDDDD",
  "DDDDDDDDDDDDDDDD",
  "DDDDxDDDDoDDDDDD",
  "DDDDDDDDDDDDDDDD",
];
