import type { Palette, PixelMap } from "../svg.ts";

export const HERO_PAL: Palette = {
  K: "#14142B",
  H: "#3B2A20",
  h: "#5C4434",
  S: "#F6C59F",
  s: "#DE9C74",
  B: "#5462E8",
  b: "#3A45B5",
  L: "#8792FF",
  W: "#FFFFFF",
  P: "#2C2F4F",
  p: "#1E2038",
  R: "#E5484D",
  r: "#A83036",
  G: "#FFC83D",
  g: "#C98A1A",
  D: "#6B6F8A",
  c: "#F2937E",
  w: "#D9DCF2",
};

/** 7 frames (16×22) بالترتيب: idle 1، idle 2، run 1، run 2، run 3، run 4، jump */
export const HERO: readonly PixelMap[] = [
  /* idle 1 */ [
    "................",
    "......KKKKK.....",
    "....KKDDHHHKK...",
    "...KHHDHhhHHHK..",
    "..KHHHDHHHHHHHK.",
    "..KHHHDHHHHHHHHK",
    "..KHHHDHHHHSSHK.",
    "..KHHKKKHSSSSSK.",
    "..KHKGGKSSSSKSK.",
    "..KHKGgKSSSSKSK.",
    "...KKKKSSSScSSK.",
    "....KSSSSSssSK..",
    ".....KKKKKKKK...",
    "....KBBWBBBBK...",
    "...KBLBBbBBBBK..",
    "...KBLBBbBBBbK..",
    "...KBBBKSsKBbK..",
    "....KbbbbbbbK...",
    "....KPPPKPPPK...",
    "....KPPK.KPPK...",
    "....KRRRKKRRRK..",
    "....KwwwKKwwwK..",
  ],
  /* idle 2 */ [
    "................",
    "................",
    "......KKKKK.....",
    "....KKDDHHHKK...",
    "...KHHDHhhHHHK..",
    "..KHHHDHHHHHHHK.",
    "..KHHHDHHHHHHHHK",
    "..KHHHDHHHHSSHK.",
    "..KHHKKKHSSSSSK.",
    "..KHKGGKSSSSKSK.",
    "..KHKGgKSSSSKSK.",
    "...KKKKSSSScSSK.",
    "....KSSSSSssSK..",
    ".....KKKKKKKK...",
    "....KBBWBBBBK...",
    "...KBLBBbBBBBK..",
    "...KBBBKSsKBbK..",
    "....KbbbbbbbK...",
    "....KPPPKPPPK...",
    "....KPPK.KPPK...",
    "....KRRRKKRRRK..",
    "....KwwwKKwwwK..",
  ],
  /* run 1 */ [
    "................",
    "......KKKKK.....",
    "....KKDDHHHKK...",
    "...KHHDHhhHHHK..",
    "..KHHHDHHHHHHHK.",
    "..KHHHDHHHHHHHHK",
    "..KHHHDHHHHSSHK.",
    "..KHHKKKHSSSSSK.",
    "..KHKGGKSSSSKSK.",
    "..KHKGgKSSSSKSK.",
    "...KKKKSSSScSSK.",
    "....KSSSSSssSK..",
    ".....KKKKKKKK...",
    "....KBBWBBBBKK..",
    "...KBLBBBBBBSsK.",
    "...KBLBBBBBBSSK.",
    "...KBBBBBBBbKK..",
    "....KbbbbbbbK...",
    "...KPPPPKKPPPK..",
    "..KPPK....KKPPK.",
    ".KRRRK.....KRRRK",
    ".KwwwK.....KwwwK",
  ],
  /* run 2 */ [
    "......KKKKK.....",
    "....KKDDHHHKK...",
    "...KHHDHhhHHHK..",
    "..KHHHDHHHHHHHK.",
    "..KHHHDHHHHHHHHK",
    "..KHHHDHHHHSSHK.",
    "..KHHKKKHSSSSSK.",
    "..KHKGGKSSSSKSK.",
    "..KHKGgKSSSSKSK.",
    "...KKKKSSSScSSK.",
    "....KSSSSSssSK..",
    ".....KKKKKKKK...",
    "....KBBWBBBBK...",
    "...KBLBBbBBBBK..",
    "...KBLBBbBBBbK..",
    "...KBBBKSsKBbK..",
    "....KbbbbbbbK...",
    ".....KPPPPPK....",
    ".....KPPKPPK....",
    "....KRRRKRRRK...",
    "....KwwwKwwwK...",
    "................",
  ],
  /* run 3 */ [
    "................",
    "......KKKKK.....",
    "....KKDDHHHKK...",
    "...KHHDHhhHHHK..",
    "..KHHHDHHHHHHHK.",
    "..KHHHDHHHHHHHHK",
    "..KHHHDHHHHSSHK.",
    "..KHHKKKHSSSSSK.",
    "..KHKGGKSSSSKSK.",
    "..KHKGgKSSSSKSK.",
    "...KKKKSSSScSSK.",
    "....KSSSSSssSK..",
    ".....KKKKKKKK...",
    "...KKBBWBBBBK...",
    "..KsSBBBBBBBBK..",
    "..KSSBLBBBBBbK..",
    "...KKBBBBBBBbK..",
    "....KbbbbbbbK...",
    "....KPPPKPPPPK..",
    "...KPPK...KPPK..",
    "...KRRRK..KRRRK.",
    "...KwwwK..KwwwK.",
  ],
  /* run 4 */ [
    "......KKKKK.....",
    "....KKDDHHHKK...",
    "...KHHDHhhHHHK..",
    "..KHHHDHHHHHHHK.",
    "..KHHHDHHHHHHHHK",
    "..KHHHDHHHHSSHK.",
    "..KHHKKKHSSSSSK.",
    "..KHKGGKSSSSKSK.",
    "..KHKGgKSSSSKSK.",
    "...KKKKSSSScSSK.",
    "....KSSSSSssSK..",
    ".....KKKKKKKK...",
    "....KBBWBBBBK...",
    "...KBLBBbBBBBK..",
    "...KBLBBbBBBbK..",
    "...KBBBKSsKBbK..",
    "....KbbbbbbbK...",
    ".....KPPPPPK....",
    ".....KPPKPPK....",
    "....KRRRKRRRK...",
    "....KwwwKwwwK...",
    "................",
  ],
  /* jump */ [
    "......KKKKK.....",
    "....KKDDHHHKK...",
    "...KHHDHhhHHHK..",
    "..KHHHDHHHHHHHK.",
    "..KHHHDHHHHHHHHK",
    "..KHHHDHHHHSSHK.",
    "..KHHKKKHSSSSSK.",
    "..KHKGGKSSSSKSK.",
    "..KHKGgKSSSSKSK.",
    "...KKKKSSSScSSK.",
    "....KSSSSSssSK..",
    ".....KKKKKKKK...",
    "....KBBWBBBBKKK.",
    "...KBLBBBBBBBSsK",
    "...KBLBBBBBBbKK.",
    "...KBBBBBBBBbK..",
    "....KbbbbbbbK...",
    "...KPPPPPPPPK...",
    "..KRRRKKKPPPK...",
    "..KwwwK.KRRRK...",
    "...KKK..KwwwK...",
    "................",
  ],
];

/** راس الشخصية (16×12): أفاتار الـ HUD، بديل الصورة الشخصية، وأيقونة الموقع */
export const HEAD: PixelMap = HERO[0].slice(1, 13);
