// node scripts/build-sprites.mjs                    ← بيكتب src/styles/pixel/sprites.generated.css
// node scripts/build-sprites.mjs --check            ← بيفحص التطابق مع المرجع وإنو الملف المولّد محدّث (ما بيكتب شي)
// node scripts/build-sprites.mjs --check --skip-reference  ← بيفحص الملف المولّد بس
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { buildExtraSpriteCss, buildSpriteCss } from "../src/pixel/sheet.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = resolve(root, "src/styles/pixel/sprites.generated.css");
const referenceFile = resolve(root, "design/pixel art.html");

const HEADER =
  "/* GENERATED by scripts/build-sprites.mjs from src/pixel. Do not edit: run `npm run sprites`. */\n";

// إضافة عن المرجع: أيقونات مش موجودة بالملف المرجعي. بتنكتب بعد ناتج المرجع، والمقارنة مع المرجع بتضل على `css` لحاله
const EXTRA_HEADER =
  "/* إضافة عن المرجع: أيقونات مش موجودة بـ design/pixel art.html (EXTRA_ICONS بـ src/pixel/sprites/icons.ts) */\n";

const css = buildSpriteCss();
const extra = buildExtraSpriteCss();
const output = `${HEADER}${css}\n${EXTRA_HEADER}${extra}\n`;
const kb = ((css.length + extra.length) / 1024).toFixed(1);

/** بيشغّل الـ boot script تبع الملف المرجعي بالذاكرة (document وهمي) وبيرجّع الـ CSS اللي بيولّده */
function referenceCss() {
  const html = readFileSync(referenceFile, "utf8");
  const match = html.match(/<script>\s*\(function \(\) \{([\s\S]*?)\}\)\(\);\s*<\/script>/);
  if (!match) throw new Error("Boot script not found in design/pixel art.html");

  let captured = "";
  const fakeDocument = {
    documentElement: { classList: { add() {}, remove() {} }, dataset: {} },
    createElement: () => ({
      set textContent(value) {
        captured = value;
      },
    }),
    head: { appendChild() {} },
  };
  const matchMedia = () => ({ matches: false });
  new Function("document", "location", "localStorage", "window", "matchMedia", match[1])(
    fakeDocument,
    { hash: "" },
    { getItem: () => null },
    { matchMedia },
    matchMedia,
  );
  return captured;
}

if (process.argv.includes("--check")) {
  const problems = [];

  if (!process.argv.includes("--skip-reference") && css !== referenceCss()) {
    problems.push("src/pixel output differs from design/pixel art.html");
  }

  let onDisk = "";
  try {
    onDisk = readFileSync(outFile, "utf8");
  } catch {
    // الملف لسا ما انولد
  }
  // git عـ Windows ممكن يحوّل LF لـ CRLF بالـ checkout
  if (onDisk.replace(/\r\n/g, "\n") !== output) {
    problems.push("sprites.generated.css is stale: run `npm run sprites`");
  }

  if (problems.length) {
    console.error(problems.map((p) => `✗ ${p}`).join("\n"));
    process.exit(1);
  }
  console.log(`✓ sprites OK (${kb}KB)`);
} else {
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, output);
  console.log(`✓ wrote ${relative(root, outFile)} (${kb}KB)`);
}
